[package]
name = "phaneros-core"
version = "0.2.1"
description = "Core engine library for file synchronization across devices."
repository = "https://github.com/asierzapata/phaneros"
homepage = "https://asierzapata.github.io/phaneros/"
keywords = ["sync", "file-synchronization", "engine", "utility"]
categories = ["command-line-utilities"]
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = true

[dependencies]
blake3 = "1.8.5"
dirs = "6.0.0"
fastcdc = "3.1"
fs2 = "0.4.3"
ignore = "0.4.23"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
phaneros-sync = { version = "0.2.1", path = "../phaneros-sync" }
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "migrate"] }
thiserror = "2.0.18"
tokio = { version = "1.53.0", features = ["full"] }
toml = "0.8.20"
reqwest = { version = "0.12", features = ["json"] }
futures = "0.3"
async-trait = "0.1"
zstd = "0.13.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = "0.7"

[dev-dependencies]
filetime = "0.2.29"
tempfile = "3.27.0"
