[package]
name = "phaneros-core"
version = "0.1.0"
description = "Core engine library for file synchronization across devices."
repository = "https://github.com/asierzapata/phaneros"
homepage = "https://asierzapata.github.io/phaneros/"
keywords = ["sync", "file-synchronization", "engine", "utility"]
categories = ["command-line-utilities"]
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = true

[dependencies]
blake3 = "1.8.5"
dirs = "6.0.0"
fs2 = "0.4.3"
ignore = "0.4.23"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
phaneros-sync = { version = "0.1.0", path = "../phaneros-sync" }
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.18"
toml = "0.8.20"
ureq = { version = "2.10.1", features = ["json"] }

[dev-dependencies]
filetime = "0.2.29"
tempfile = "3.27.0"
