[workspace]
resolver = "2"
members = [
    "crates/phaneros-core",
    "crates/phaneros-daemon",
    "crates/phaneros-cli",
    "crates/phaneros-ipc",
    "crates/phaneros-sync",
    "crates/phaneros-store",
    "crates/phaneros-desktop/src-tauri",
]

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
authors = ["Asier Zapata <me@asierzapata.com>"]
repository = "https://github.com/asierzapata/phaneros"
homepage = "https://asierzapata.github.io/phaneros/"
publish = false

[workspace.dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo-release'
[workspace.metadata.release]
shared-version = true
consolidate-commits = true
tag-name = "v{{version}}"
publish = false
