[package]
name = "phaneros-desktop"
version = "0.1.0"
description = "Phaneros Desktop application powered by Tauri."
repository = "https://github.com/asierzapata/phaneros"
homepage = "https://asierzapata.github.io/phaneros/"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "phaneros_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
phaneros-core = { version = "0.1.0", path = "../../phaneros-core" }
phaneros-ipc = { version = "0.1.0", path = "../../phaneros-ipc" }
dirs = "6.0.0"
tokio = { version = "1.53.0", features = ["fs"] }
blake3 = "1.8.5"
similar = "2"

[dev-dependencies]
tempfile = "3.27.0"

